# Generated by Django 2.2.7 on 2019-11-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_no',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='unit',
            name='cell_no',
            field=models.CharField(max_length=12),
        ),
    ]
