# Generated by Django 2.2.7 on 2019-12-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dock', '0002_auto_20191121_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
